# Development overrides for Docker Compose
# Automatically loaded when using docker compose in development

services:
  frontend:
    build:
      target: development
    container_name: riot_api_app_frontend_dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  backend:
    build:
      target: development
    container_name: riot_api_app_backend_dev
    user: "1001:1001"
    environment:
      LOG_LEVEL: DEBUG
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ENVIRONMENT: dev
      WATCHFILES_FORCE_POLLING: "true"
      UV_CACHE_DIR: /tmp/.uv-cache
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
